"""Pytest configuration and fixtures for Insights tests."""

import pytest
from pathlib import Path
from typing import Any
from unittest.mock import MagicMock


@pytest.fixture
def sample_report_html() -> str:
    """Sample HTML report content."""
    return """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test Report - Insights Report</title>
</head>
<body>
    <header>
        <h1>Test Report</h1>
        <p>Generated: 2024-01-01T00:00:00 | Run: 1</p>
    </header>
    <nav id="toc">
        <h2>Contents</h2>
        <ul>
            <li><a href="#repo_health">Repository Health Overview</a></li>
        </ul>
    </nav>
    <main>
        <section id="repo_health" class="report-section">
            <h2>Repository Health Overview</h2>
            <div class="metric-card">
                <div class="label">Total Files</div>
                <div class="value">150</div>
            </div>
        </section>
    </main>
    <footer>
        <p>Generated by Project Vulcan Insights</p>
    </footer>
</body>
</html>"""


@pytest.fixture
def sample_report_md() -> str:
    """Sample Markdown report content."""
    return """# Test Report

**Generated:** 2024-01-01T00:00:00
**Run:** 1

---

## Table of Contents

- [Repository Health Overview](#repo-health)

---

## Repository Health Overview

| Metric | Value |
|--------|-------|
| Total Files | 150 |
| Total Lines of Code | 25,000 |

---

*Generated by Project Vulcan Insights*"""


@pytest.fixture
def sample_repo_health_data() -> dict[str, Any]:
    """Sample repo health data."""
    return {
        "total_files": 150,
        "total_loc": 25000,
        "total_code": 20000,
        "total_comment": 3000,
        "avg_ccn": 4.5,
        "max_ccn": 25,
        "health_grade": "B",
        "violation_count": 2,
        "lfs_candidate_count": 0,
        "languages": [
            {"language": "Python", "file_count": 80, "loc": 15000},
            {"language": "JavaScript", "file_count": 40, "loc": 8000},
        ],
        "has_health_grade": True,
    }


@pytest.fixture
def sample_vulnerability_data() -> dict[str, Any]:
    """Sample vulnerability data."""
    return {
        "summary": [
            {"severity": "CRITICAL", "count": 2, "affected_packages": 2, "unique_cves": 2},
            {"severity": "HIGH", "count": 5, "affected_packages": 3, "unique_cves": 5},
            {"severity": "MEDIUM", "count": 10, "affected_packages": 5, "unique_cves": 10},
        ],
        "top_cves": [
            {
                "cve_id": "CVE-2024-0001",
                "severity": "CRITICAL",
                "package_name": "vulnerable-pkg",
                "installed_version": "1.0.0",
                "fixed_version": "1.0.1",
                "title": "Critical vulnerability",
            },
        ],
        "affected_packages": [
            {
                "package_name": "vulnerable-pkg",
                "installed_version": "1.0.0",
                "total_vulns": 3,
                "critical_count": 1,
                "high_count": 1,
                "medium_count": 1,
            },
        ],
        "total_count": 17,
        "critical_count": 2,
        "high_count": 5,
        "has_vulnerabilities": True,
        "has_critical": True,
        "risk_level": "critical",
    }


@pytest.fixture
def mock_fetcher() -> MagicMock:
    """Mock DataFetcher."""
    fetcher = MagicMock()
    fetcher.fetch.return_value = []
    fetcher.fetch_raw.return_value = []
    fetcher.table_exists.return_value = True
    return fetcher
