#!/usr/bin/env python3
"""Create GitHub issues from risk register entries using the gh CLI.

Reads high/critical risks from lz_risks in DuckDB and creates GitHub issues.
Dry-run by default — use ``--apply`` to actually create issues.

Usage::

    # Dry-run: preview issues that would be created
    python scripts/create_risk_issues.py --db ~/.caldera/caldera_sot.duckdb

    # Create issues for a specific run
    python scripts/create_risk_issues.py --db ~/.caldera/caldera_sot.duckdb \\
        --collection-run-id <uuid> --apply

    # Only critical risks
    python scripts/create_risk_issues.py --db ~/.caldera/caldera_sot.duckdb \\
        --min-severity critical --apply
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

import duckdb

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3}
DEFAULT_LABELS = ["risk", "caldera"]


def _fetch_risks(
    conn: duckdb.DuckDBPyConnection,
    collection_run_id: str | None,
    min_severity: str,
) -> list[dict[str, str | None]]:
    """Fetch risks at or above *min_severity* from lz_risks."""
    threshold = SEVERITY_ORDER.get(min_severity, 1)
    allowed = [s for s, v in SEVERITY_ORDER.items() if v <= threshold]
    placeholders = ", ".join("?" for _ in allowed)

    if collection_run_id:
        query = f"""
            SELECT risk_id, description, technical_cause, manifests_in,
                   triggered_by, severity, action, sla_date, status
            FROM lz_risks
            WHERE collection_run_id = ?
              AND severity IN ({placeholders})
            ORDER BY
                CASE severity
                    WHEN 'critical' THEN 0
                    WHEN 'high' THEN 1
                    WHEN 'medium' THEN 2
                    WHEN 'low' THEN 3
                END
        """
        params = [collection_run_id, *allowed]
    else:
        # Pick the latest collection run
        query = f"""
            SELECT r.risk_id, r.description, r.technical_cause, r.manifests_in,
                   r.triggered_by, r.severity, r.action, r.sla_date, r.status
            FROM lz_risks r
            JOIN lz_collection_runs cr ON r.collection_run_id = cr.collection_run_id
            WHERE r.severity IN ({placeholders})
            ORDER BY cr.started_at DESC,
                CASE r.severity
                    WHEN 'critical' THEN 0
                    WHEN 'high' THEN 1
                    WHEN 'medium' THEN 2
                    WHEN 'low' THEN 3
                END
        """
        params = list(allowed)

    rows = conn.execute(query, params).fetchall()
    results: list[dict[str, str | None]] = []
    for row in rows:
        results.append({
            "risk_id": row[0],
            "description": row[1],
            "technical_cause": row[2],
            "manifests_in": row[3],
            "triggered_by": row[4],
            "severity": row[5],
            "action": row[6],
            "sla_date": row[7],
            "status": row[8],
        })
    return results


def _build_issue_title(risk: dict[str, str | None]) -> str:
    return f"[{risk['risk_id']}] {risk['description']}"


def _build_issue_body(risk: dict[str, str | None]) -> str:
    lines = [
        f"## {risk['triggered_by']}",
        "",
        f"**Severity:** {risk['severity']}",
        f"**Status:** {risk['status'] or 'open'}",
        "",
        "### Description",
        "",
        risk["description"] or "",
        "",
        "### Technical Cause",
        "",
        risk["technical_cause"] or "Not specified",
        "",
    ]

    if risk.get("action"):
        lines += ["### Suggested Action", "", risk["action"], ""]

    if risk.get("sla_date"):
        lines += [f"**SLA Date:** {risk['sla_date']}", ""]

    manifests = risk.get("manifests_in") or ""
    if manifests:
        locations = [loc.strip() for loc in manifests.split(",") if loc.strip()]
        if locations:
            lines += ["### Affected Locations", ""]
            for loc in locations[:10]:
                lines.append(f"- `{loc}`")
            if len(locations) > 10:
                lines.append(f"- ... and {len(locations) - 10} more")
            lines.append("")

    lines += [
        "---",
        "*Generated by [Project Caldera](https://github.com/alexander-stage-hoco/project-caldera) risk register*",
    ]
    return "\n".join(lines)


def _existing_issue_titles(repo: str | None) -> set[str]:
    """Search for existing Caldera risk issues to avoid duplicates."""
    cmd = ["gh", "issue", "list", "--label", "caldera", "--state", "all", "--json", "title", "--limit", "200"]
    if repo:
        cmd += ["--repo", repo]

    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        return set()

    try:
        issues = json.loads(result.stdout)
        return {issue["title"] for issue in issues}
    except (json.JSONDecodeError, KeyError):
        return set()


def _create_issue(
    title: str,
    body: str,
    labels: list[str],
    repo: str | None,
) -> str | None:
    """Create a GitHub issue via gh CLI. Returns the issue URL or None on failure."""
    cmd = ["gh", "issue", "create", "--title", title, "--body", body]
    for label in labels:
        cmd += ["--label", label]
    if repo:
        cmd += ["--repo", repo]

    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        print(f"  ERROR: {result.stderr.strip()}", file=sys.stderr)
        return None
    return result.stdout.strip()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Create GitHub issues from risk register entries."
    )
    parser.add_argument("--db", required=True, help="Path to DuckDB file")
    parser.add_argument(
        "--collection-run-id",
        default=None,
        help="Specific collection run ID (default: latest)",
    )
    parser.add_argument(
        "--min-severity",
        default="high",
        choices=["critical", "high", "medium", "low"],
        help="Minimum severity to create issues for (default: high)",
    )
    parser.add_argument(
        "--repo",
        default=None,
        help="GitHub repo (owner/name) to create issues in (default: current repo)",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        default=False,
        help="Actually create issues (default: dry-run)",
    )
    args = parser.parse_args()

    db_path = Path(args.db).expanduser().resolve()
    if not db_path.exists():
        print(f"ERROR: DuckDB file not found: {db_path}", file=sys.stderr)
        return 1

    conn = duckdb.connect(str(db_path), read_only=True)
    try:
        risks = _fetch_risks(conn, args.collection_run_id, args.min_severity)
    finally:
        conn.close()

    if not risks:
        print("No risks found matching criteria.")
        return 0

    print(f"Found {len(risks)} risk(s) at severity >= {args.min_severity}")
    print()

    # Check for existing issues to deduplicate
    existing = _existing_issue_titles(args.repo) if args.apply else set()

    created = 0
    skipped = 0
    for risk in risks:
        title = _build_issue_title(risk)
        body = _build_issue_body(risk)
        labels = DEFAULT_LABELS + [f"severity:{risk['severity']}"]

        if title in existing:
            print(f"  SKIP (exists): {title}")
            skipped += 1
            continue

        if args.apply:
            url = _create_issue(title, body, labels, args.repo)
            if url:
                print(f"  CREATED: {title}")
                print(f"           {url}")
                created += 1
        else:
            print(f"  [DRY-RUN] Would create: {title}")
            print(f"            Severity: {risk['severity']}")
            if risk.get("action"):
                print(f"            Action: {risk['action']}")
            if risk.get("sla_date"):
                print(f"            SLA: {risk['sla_date']}")
            print()

    print()
    if args.apply:
        print(f"=== Summary: {created} created, {skipped} skipped (already exist) ===")
    else:
        print(f"=== Dry-run: {len(risks) - skipped} issue(s) would be created ===")
        print("    Use --apply to create issues.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
